pg:
  host: localhost
  port: 5434
  user: postgres
  password: postgres
  database: postgres_test

storage_dir: file_storage

#pg:
#  host: test_db
#  port: 5432
#  user: postgres
#  password: postgres
#  database: postgres_123



timezone: 'Europe/Moscow'

