services:
  files:
    image: 'files:latest'
    depends_on:
      - postgres
    build:
      context: ./
    volumes:
      - .:/src/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    expose:
      - 8001
    ports:
      - "8023:8001"
    networks:
      - image-processing-net
    command: ["python", "./src/app.py"]

  postgres:
    image: postgres:17-bookworm
    volumes:
      - test_pgdata:/var/lib/postgresql/data/pgdata
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    expose:
      - 5432
    ports:
      - "5434:5432"
    networks:
      - image-processing-net

volumes:
  test_pgdata:

networks:
  image-processing-net:
    name: image-processing-net