services:
  files:
    image: files:latest
    depends_on:
      - postgres
    volumes:
      - ./file_storage:/file_storage
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
      - 8023:80
    networks:
      - image-processing-net

  postgres:
    image: postgres:17-bookworm
    volumes:
      - test_pgdata:/var/lib/postgresql/data/pgdata
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5434:5432"
    networks:
      - image-processing-net

volumes:
  test_pgdata:

networks:
  image-processing-net:
    name: image-processing-net