services:
  backend:
    container_name: test_backend
    image: 'test_backend:latest'
    depends_on:
      - test_db
    build:
      context: ./
    volumes:
      - .:/src/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
      - "8023:8001"
    command: ["python", "./src/app.py"]

  test_db:
    container_name: test_db
    image: postgres:17-bookworm
    volumes:
      - test_pgdata:/var/lib/postgresql/data/pgdata
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    expose:
      - 5432
    ports:
      - "5434:5432"
volumes:
  test_pgdata: